project:
  type: website

website:
  title: "Mortality Aotearoa"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: deaths.qmd
        text: Deaths
      - href: popn.qmd
        text: Population

format:
  html:
    theme: cosmo
    toc: true

execute:
  echo: false